notifications:
  email: false

sudo: false

dist: bionic

language: cpp

addons:
  apt:
    packages:
    - clang-format
    - doxygen
    - graphviz
    - lcov

jobs:
  include:
    - stage: checks
      script: ./check_styleguide.sh
    - stage: build
      script: ./build.sh
      after_script:
      - ./generate_coverage.sh
      - ./upload_report_ci.sh
      - ./upload_codecov.sh
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./build/doc_doxygen/html
          github_token: $GITHUB_TOKEN
          on:
            branch: master