notifications:
  email: false

sudo: false

dist: bionic

language: cpp

addons:
  apt:
    packages: lcov

script:
- ./build.sh

after_script:
- ./generate_coverage.sh
- ./upload_report_ci.sh
- ./upload_codecov.sh
