notifications:
  email: false

sudo: false

dist: bionic

language: cpp

services:
  - docker

env:
  - DOCKER_CONTAINER=thorshamster/file2passwd:latest

before_install:
  - docker pull ${DOCKER_CONTAINER}

jobs:
  include:
    - stage: checks
      script: ./check_styleguide.sh -r
    - stage: build
      script: docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./build.sh
      after_script:
      - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./generate_coverage.sh
      - report_ci_env=`bash <report_ci_env`
      - docker run $report_ci_env --env TRAVIS_BUILD_DIR=/usr/project/ --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./upload_report_ci.sh
      - ci_env=`bash <(curl -s https://codecov.io/env)`
      - docker run $ci_env --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./upload_codecov.sh
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: ./build/doc_doxygen/html
          github_token: $GITHUB_TOKEN
          on:
            branch: master