name: build

on: push

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    container: 
      image: thorshamster/file2passwd:latest
      volumes:
        - /home/runner/work:/usr/project

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run styleguide checks
        run: ./check_styleguide.sh -r

      - name: build
        run: ./build.sh

      - name: build unittest
        run: ./build_unittests.sh

      - name: generate coverage
        run: ./generate_coverage.sh

      - name: upload to codecov
        uses: codecov/codecov-action@v1
