name: Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: 
      image: thorshamster/file2passwd:latest
      volumes:
      - /home/runner/work:/usr/project

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./build.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: thorshamster/file2passwd:latest
      volumes:
      - /home/runner/work:/usr/project

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Styleguide Checks
        run: ./check_styleguide.sh -r

      - name: Build Unittest
        run: ./build_unittests.sh

      - name: Run all Unittest
        run: ./run_all_unittests.sh

      - name: Generate Coverage
        run: ./generate_coverage.sh

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1

      - name: Upload to ReportCI
        run: ./upload_report_ci.sh
        runs-on: ubuntu-latest
