name: build

on: push

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    container: 
      image: thorshamster/file2passwd:latest
      volumes:
        - /home/runner/work:/usr/project
      env:
        CI: ${{ env.CI }}
        GITHUB_WORKFLOW: ${{ env.GITHUB_WORKFLOW }}
        GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
        GITHUB_RUN_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
        GITHUB_ACTION: ${{ env.GITHUB_ACTION }}
        GITHUB_ACTIONS: ${{ env.GITHUB_ACTIONS }}
        GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        GITHUB_EVENT_NAME: ${{ env.GITHUB_EVENT_NAME }}
        GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
        GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
        GITHUB_REF: ${{ env.GITHUB_REF }}
        GITHUB_HEAD_REF: ${{ env.GITHUB_HEAD_REF }}
        GITHUB_BASE_REF: ${{ env.GITHUB_BASE_REF }}
        GITHUB_SERVER_URL: ${{ env.GITHUB_SERVER_URL }}
        GITHUB_API_URL: ${{ env.GITHUB_API_URL }}
        GITHUB_GRAPHQL_URL: ${{ env.GITHUB_GRAPHQL_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run styleguide checks
        run: ./check_styleguide.sh -r

      - name: build
        run: ./build.sh

      - name: build unittest
        run: ./build_unittests.sh

      - name: generate coverage
        run: ./generate_coverage.sh

      - name: upload to codecov
        uses: codecov/codecov-action@v1

      - name: Upload to ReportCI
        run: ./upload_report_ci.sh
