name: build

on: push

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    container: 
      image: thorshamster/file2passwd:latest
      volumes:
        - /home/runner/work:/usr/project
      env:
        CI: ${{ env.CI }}
        CI_BUILD_URL: ${{ env.CI_BUILD_URL }}
        CI_BUILD_ID: ${{ env.CI_BUILD_ID }}
        CI_JOB_ID: ${{ env.CI_JOB_ID }}
        GITHUB_ACTION: ${{ env.GITHUB_ACTION }}
        GITHUB_REF: ${{ env.GITHUB_REF }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        GITHUB_HEAD_REF: ${{ env.GITHUB_HEAD_REF }}
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
        GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
        GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
        GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
        TRAVIS_BUILD_DIR: /usr/project/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run styleguide checks
        run: ./check_styleguide.sh -r

      - name: build
        run: ./build.sh

      - name: build unittest
        run: ./build_unittests.sh

      - name: generate coverage
        run: ./generate_coverage.sh

      - name: upload to codecov
        uses: codecov/codecov-action@v1

      - name: Upload to ReportCI
        run: ./upload_report_ci.sh
