name: Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Build - ${{ github.event_name }}
    runs-on: ubuntu-latest
    container:
      image: thorshamster/file2passwd:latest
      volumes:
      - /home/runner/work:/usr/project

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: ./build.sh

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: file2passwd
          path: ${{ github.workspace }}/_install/bin/
          retention-days: 5

      - name: Deploy
        if: success() && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc_doxygen/html

  test:
    name: Test - ${{ github.event_name }}
    runs-on: ubuntu-latest
    container:
      image: thorshamster/file2passwd:latest
      volumes:
      - /home/runner/work:/usr/project

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Styleguide Checks
        run: ./check_styleguide.sh -r

      - name: Build Unittest
        run: ./build_unittests.sh

      - name: Run all Unittest
        run: ./run_all_unittests.sh

      - name: Generate Coverage
        run: ./generate_coverage.sh

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v4

      - name: Upload to ReportCI
        run: ./upload_report_ci.sh
        if: github.event_name == 'push'
