name: build

on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Styleguide Checks
        run: ./check_styleguide.sh -r
        container: 
          image: thorshamster/file2passwd:latest
          volumes:
          - /home/runner/work:/usr/project

      - name: Build
        run: ./build.sh
        container: 
          image: thorshamster/file2passwd:latest
          volumes:
          - /home/runner/work:/usr/project

      - name: Build Unittest
        run: ./build_unittests.sh
        container: 
          image: thorshamster/file2passwd:latest
          volumes:
          - /home/runner/work:/usr/project

      - name: Run all Unittest
        run: ./run_all_unittests.sh
        container: 
          image: thorshamster/file2passwd:latest
          volumes:
          - /home/runner/work:/usr/project

      - name: Generate Coverage
        run: ./generate_coverage.sh
        container: 
          image: thorshamster/file2passwd:latest
          volumes:
          - /home/runner/work:/usr/project

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1

      - name: Upload to ReportCI
        run: ./upload_report_ci.sh
